--CREATE DATABASE HOMEWORK
--USE HOMEWORK


CREATE TABLE ROLES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100) NOT NULL 
)


CREATE TABLE USERS(
NAMEUSERSID INT REFERENCES ROLES(Id),
ROLES INT NOT NULL UNIQUE,
ID INT PRIMARY KEY IDENTITY,
USERNAME NVARCHAR(100) NOT NULL,
PASSWORD INT CHECK(PASSWORD>=8)
)


INSERT INTO ROLES VALUES(N'ADMIN'),(N'MODERATOR')
SELECT * FROM ROLES

INSERT INTO USERS VALUES('ABBASOVNURLAN',12345678)
SELECT * FROM USERS

SELECT U.USERNAME AS 'NAMEUSER', R.NAME AS ROLES FROM USERS AS U
INNER JOIN ROLES AS R
ON U.NAMEUSERSID=R.ID



CREATE TABLE PRODUCTS(
Id INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100) NOT NULL UNIQUE,
PRICE DECIMAL CHECK(Price>0), 
COST INT CHECK(COST>0),
)


CREATE TABLE CATEGORIES(
Id INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100) NOT NULL UNIQUE
)


CREATE TABLE SIZES(
Id INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100) NOT NULL UNIQUE
)

INSERT INTO PRODUCTS VALUES(N'PEPSI'),(N'CIPS')
SELECT * FROM PRODUCTS


INSERT INTO CATEGORIES VALUES(N'YIMEY'),(N'ICGI')
SELECT * FROM CATEGORIES

INSERT INTO SIZES VALUES('MINI'),('MEDIUM')
SELECT * FROM SIZES


SELECT P.NAME AS PRODUCTNAME,P.PRICE AS PRODUCTPRIZE,C.NAME AS CATEGORYNAME, S.NAME AS PRODUCTSIZE
FROM CATEGORIES AS C
RIGHT JOIN PRODUCTS AS P
ON C.ID=P.CATEGORYID
LEFT JOIN SIZES AS PS
ON PS.PRODUCTID=P.ID
LEFT JOIN SIZES AS S
ON PS.SIZESID=S.ID